services:
  mediatr.webapi:
    image: ${DOCKER_REGISTRY-}mediatrwebapi
    container_name: mediatr.webapi
    build:
      context: .
      dockerfile: Mediatr.WebApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    restart: always
    depends_on:
      - mediatr.postgres
    networks:
      - app_network

  mediatr.postgres:
    image: postgres:latest
    container_name: mediatr.postgres
    # restart: unless-stopped
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todoDb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - C:/Temp/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U myuser"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: "512M"
    #     reservations:
    #       cpus: "0.5"
    #       memory: "256M"

networks:
  app_network:
    driver: bridge
